import type { Drill } from "./types";

export const PILLAR_LABEL: Record<Drill["pillar"], string> = {
  ball: "On the ball",
  shooting: "Shooting",
  passing: "Passing",
  speed: "Speed",
  agility: "Agility",
  strength: "Strength",
};

export const DRILLS: Drill[] = [
  {
    id: "act-dynamic",
    name: "Activation strides",
    pillar: "speed",
    focus: "Prime the first step without frying the legs",
    setup: "20m lane. Jog out, walk back. Open the hips, then add A-skips and two build-up strides.",
    equipment: ["cones"],
    cues: [
      "Tall posture, quiet feet on the jog",
      "Drive the knee, strike under the hip on skips",
      "Last two strides are 70 percent — not a race",
    ],
    why: "Elite sessions start warm and sharp. This is the on-switch, not the workout.",
    timer: { kind: "interval", workSec: 40, restSec: 20, sets: 4 },
    score: "none",
    targetNote: "Feel springy, not gassed",
    space: "20m lane",
    modes: {
      solo: { setup: "Mark 20m with two cones or backpacks.", cue: "Count quality strides, not speed." },
      partner: { setup: "Side by side in the same lane.", cue: "Match posture, not each other's ego." },
      trainer: { setup: "Coach the posture from the side.", cue: "Stop the set if heels stay heavy." },
    },
  },
  {
    id: "ball-foundation",
    name: "Foundation touches",
    pillar: "ball",
    focus: "Inside, outside, sole — both feet, head up",
    setup: "2x2m box. Ball glued to the foot. Sequence: inside-inside, outside rolls, sole rolls, V-pulls.",
    equipment: ["ball", "cones"],
    cues: [
      "Soft ankle, heavy ball is a dead ball",
      "Scan up every third touch",
      "Same quality on the weak foot — slow it down first",
    ],
    why: "Every elite 13-year-old owns the first two touches. This is the daily standard.",
    timer: { kind: "metronome", workSec: 45, restSec: 15, sets: 6, bpm: 80 },
    score: "reps",
    scoreLabel: "Clean sequences",
    targetNote: "One clean sequence per foot without a heavy touch",
    space: "2x2m",
    modes: {
      solo: { setup: "Box of four cones, phone outside the box.", cue: "If the ball leaves the box, reset the count." },
      partner: { setup: "Mirror each other, 3m apart.", cue: "Call 'up' — partner must look up on the next touch." },
      trainer: { setup: "Coach stands in front and holds up fingers.", cue: "Player shouts the number without killing the ball." },
    },
  },
  {
    id: "ball-cone-weave",
    name: "Tight weave",
    pillar: "ball",
    focus: "Close control through a 1m gate line",
    setup: "Six cones, 1m apart. Weave both directions. Explode 5m off the last cone.",
    equipment: ["ball", "cones"],
    cues: [
      "Touches with the far foot through the gate",
      "Hips stay facing the line — don't spin out",
      "Last cone is a change of pace, not a bigger touch until you're clear",
    ],
    why: "U13/U14 games get tight. The player who can play in a phone booth wins the duel.",
    timer: { kind: "interval", workSec: 30, restSec: 25, sets: 8 },
    score: "time",
    scoreLabel: "Best clean run",
    targetNote: "Fastest clean weave + 5m exit",
    space: "12m line",
    modes: {
      solo: { setup: "Time each clean run. Missed cone does not count.", cue: "Chase your own last clean time." },
      partner: { setup: "Relay. Partner starts when you hit the exit cone.", cue: "No false starts — ball must be rolling." },
      trainer: { setup: "Coach can shrink spacing to 0.8m late in the block.", cue: "Quality first. Speed is earned." },
    },
  },
  {
    id: "ball-first-touch",
    name: "Directional first touch",
    pillar: "ball",
    focus: "Take the ball where you already want to go",
    setup: "5m triangle. Serve (throw or wall) into the middle. First touch out of the triangle toward a colored cone, then recover.",
    equipment: ["ball", "cones", "wall"],
    cues: [
      "Decide the exit before the ball arrives",
      "Cushion, then push — one motion",
      "Open the hips toward the next action",
    ],
    why: "First touch is a pass to yourself. Elite players don't trap and then think.",
    timer: { kind: "interval", workSec: 40, restSec: 20, sets: 6 },
    score: "makes",
    scoreLabel: "Clean exits",
    targetNote: "Touch stays inside a 2m channel toward the target cone",
    space: "8x8m",
    modes: {
      solo: { setup: "Use a wall or self-toss. Call the color before contact.", cue: "If you didn't call it, it doesn't count." },
      partner: { setup: "Partner serves varied pace, two-handed toss.", cue: "Server mixes height after set 3." },
      trainer: { setup: "Coach points to the exit on the way in.", cue: "Late point. Force a real decision." },
    },
  },
  {
    id: "ball-1v1-moves",
    name: "1v1 move library",
    pillar: "ball",
    focus: "Body feint, scissors, stop-and-go — then explode",
    setup: "10m channel, one 'defender' cone at 6m. Approach, execute, exit at match pace for 4m.",
    equipment: ["ball", "cones"],
    cues: [
      "Sell with the hips, not a giant step-over",
      "The move is nothing without the exit touch",
      "Protect the ball with the body on the way out",
    ],
    why: "At 13, 1v1 is still a separator. Learn three moves perfectly, not twelve sloppy.",
    timer: { kind: "interval", workSec: 25, restSec: 20, sets: 8 },
    score: "quality",
    scoreLabel: "Exit quality",
    targetNote: "Clean exit into a 2m gate",
    space: "12m channel",
    modes: {
      solo: { setup: "Cone is the defender. Alternate moves each rep.", cue: "Film one set if you can — check the hip fake." },
      partner: { setup: "Live passive defender, then 50 percent pressure.", cue: "Defender stays on their feet. No slide." },
      trainer: { setup: "Coach names the move two steps before.", cue: "Then go live on the last two sets." },
    },
  },
  {
    id: "ball-juggle",
    name: "Aerial control",
    pillar: "ball",
    focus: "Juggle with a purpose — instep, thigh, weak foot",
    setup: "Stay inside a 3x3m box. Pattern: 4 instep, 2 thigh, 2 weak-foot. Catch and reset if it drops.",
    equipment: ["ball"],
    cues: [
      "Toe down, ankle locked on the instep",
      "Let the ball come to you — don't stab",
      "Weak foot gets the same height, not a panic pop",
    ],
    why: "Aerial comfort shows up on clearances, half-volleys, and ugly first touches in the air.",
    timer: { kind: "interval", workSec: 45, restSec: 15, sets: 5 },
    score: "reps",
    scoreLabel: "Longest clean pattern",
    targetNote: "Beat last session's streak",
    space: "3x3m",
    modes: {
      solo: { setup: "Stay in the box. Drop = reset the streak.", cue: "Count out loud. Honesty is the drill." },
      partner: { setup: "Share one ball. 4 each, then play it up for the other.", cue: "Give a catchable ball." },
      trainer: { setup: "Coach calls the surface mid-juggle.", cue: "Reward control, not circus tricks." },
    },
  },
  {
    id: "ball-turn-escape",
    name: "Turn and escape",
    pillar: "ball",
    focus: "Inside hook, Cruyff, outside cut — play away from pressure",
    setup: "Gate at 8m. Dribble in, turn on a cone, exit through a side gate.",
    equipment: ["ball", "cones"],
    cues: [
      "Check the shoulder before the turn",
      "The turn is a disguise — exit on the next stride",
      "Keep the ball on the safe side of your body",
    ],
    why: "Receiving with your back to goal is weekly. The turn is how you become a problem.",
    timer: { kind: "interval", workSec: 30, restSec: 20, sets: 6 },
    score: "makes",
    scoreLabel: "Clean escapes",
    targetNote: "Shoulder check + clean exit gate",
    space: "10x10m",
    modes: {
      solo: { setup: "Call the turn before you arrive.", cue: "No shoulder check, no count." },
      partner: { setup: "Partner shadows from behind at 60 percent.", cue: "Escape the shadow, don't barge." },
      trainer: { setup: "Coach approaches from a random shoulder.", cue: "Turn away from the pressure every time." },
    },
  },
  {
    id: "pass-wall-rhythm",
    name: "Wall rhythm",
    pillar: "passing",
    focus: "Two-touch, then one-touch, both feet",
    setup: "6–8m from a wall or rebounder. Alternate feet. Driven, not scooped.",
    equipment: ["ball", "wall"],
    cues: [
      "Plant foot at the target",
      "Ankle locked, follow through at the wall",
      "One-touch only when the weight is right",
    ],
    why: "Passing accuracy is a rhythm skill. The wall never lies.",
    timer: { kind: "metronome", workSec: 40, restSec: 20, sets: 6, bpm: 70 },
    score: "makes",
    scoreLabel: "Clean returns in a row",
    targetNote: "Hit a 1m gate drawn or imagined on the wall",
    space: "8m to a wall",
    modes: {
      solo: { setup: "Chalk or tape a 1m target on the wall.", cue: "Miss the target and restart the streak." },
      partner: { setup: "Face each other at 10m if no wall.", cue: "Same rhythm. Talk the weight." },
      trainer: { setup: "Coach calls 1-touch / 2-touch live.", cue: "Weight first. Tempo second." },
    },
  },
  {
    id: "pass-driven",
    name: "Driven 15",
    pillar: "passing",
    focus: "Laces-driven ball that stays playable",
    setup: "Two gates 15–18m apart. Drive through the gate. Collect, reset, other foot.",
    equipment: ["ball", "cones"],
    cues: [
      "Lean over the ball — no Hollywood lean-back",
      "Strike through the equator",
      "The ball should arrive on a bounce the teammate can play",
    ],
    why: "U14 games stretch. The driven ball switches play and breaks lines.",
    timer: { kind: "reps", workSec: 0, restSec: 15, sets: 8 },
    score: "makes",
    scoreLabel: "Gates hit",
    targetNote: "8 each foot through a 2m gate",
    space: "20m",
    modes: {
      solo: { setup: "Hit a gate, chase, hit back.", cue: "Log only the ones that stay below knee height." },
      partner: { setup: "Play through the gate to each other.", cue: "Receiver rates the weight 1–5." },
      trainer: { setup: "Coach stands in the lane as a dummy midfielder.", cue: "Must miss the coach and still find the gate." },
    },
  },
  {
    id: "pass-weak-foot",
    name: "Weak-foot service",
    pillar: "passing",
    focus: "Inside-foot accuracy with the non-dominant foot",
    setup: "Three small gates at 8, 12, and 16m. Only weak foot. Work near to far.",
    equipment: ["ball", "cones"],
    cues: [
      "Plant closer than you think",
      "Hip through the ball, not a stab",
      "Start slower — accuracy before whip",
    ],
    why: "A 13-year-old who can play both ways is already selected differently.",
    timer: { kind: "interval", workSec: 50, restSec: 25, sets: 5 },
    score: "makes",
    scoreLabel: "Weak-foot gates",
    targetNote: "12 clean weak-foot passes",
    space: "18m",
    modes: {
      solo: { setup: "Retrieve your own misses. That's the tax.", cue: "Do not sneak a strong-foot rescue." },
      partner: { setup: "Partner is a moving target inside a 3m box.", cue: "Lead them. Don't pass to where they were." },
      trainer: { setup: "Coach only collects clean balls.", cue: "Ugly contact means replay, not progress." },
    },
  },
  {
    id: "pass-combo",
    name: "Give-and-go pattern",
    pillar: "passing",
    focus: "Pass, move, receive in stride",
    setup: "L-shape cones. Pass to wall/partner, spin around the cone, take it in stride, finish with a driven ball.",
    equipment: ["ball", "cones", "wall"],
    cues: [
      "The movement starts as the ball leaves",
      "Check the shoulder on the way around the cone",
      "Receive across the body so the next pass is already on",
    ],
    why: "Combinations are how small players control big games.",
    timer: { kind: "interval", workSec: 35, restSec: 25, sets: 6 },
    score: "makes",
    scoreLabel: "Clean patterns",
    targetNote: "Pass + move + in-stride receive",
    space: "15x10m",
    modes: {
      solo: { setup: "Wall is the teammate. Set the angle so the return is playable.", cue: "If you stop the ball dead, the pattern failed." },
      partner: { setup: "Live one-two. Swap roles every set.", cue: "Talk. 'Set' and 'go' are part of the skill." },
      trainer: { setup: "Coach times the return to be slightly awkward.", cue: "Adjust the body, don't blame the pass." },
    },
  },
  {
    id: "shot-placement",
    name: "Placement finishing",
    pillar: "shooting",
    focus: "Near post / far post with the inside foot",
    setup: "Two cone targets in a goal or 3m gate. Start at 12m. Alternate posts. Two-touch max.",
    equipment: ["ball", "cones", "goal"],
    cues: [
      "Eyes on the ball at contact, then the target",
      "Ankle locked, punch through the inside",
      "Plant foot points where the ball should die",
    ],
    why: "Accuracy beats power at this age. Keepers at U13 still get beaten by the corners.",
    timer: { kind: "reps", workSec: 0, restSec: 12, sets: 10 },
    score: "makes",
    scoreLabel: "Targets hit",
    targetNote: "7/10 on the called post",
    space: "Penalty area",
    modes: {
      solo: { setup: "Collect your rebounds. Call the post out loud.", cue: "No call, no count." },
      partner: { setup: "Partner serves from the side, then becomes keeper if you have gloves.", cue: "Serve to the back foot." },
      trainer: { setup: "Coach points to the post as you take the touch.", cue: "Late call. Decision under a clock." },
    },
  },
  {
    id: "shot-driven",
    name: "Driven low finish",
    pillar: "shooting",
    focus: "Laces, low, across the keeper",
    setup: "Start at 16–18m. One prep touch out of the feet, strike low to the far-side cone.",
    equipment: ["ball", "cones", "goal"],
    cues: [
      "Head steady, chest over the ball",
      "Strike the middle-low third",
      "Follow through toward the far post, not the sky",
    ],
    why: "The low driven ball is the most repeatable goal in youth soccer.",
    timer: { kind: "reps", workSec: 0, restSec: 15, sets: 8 },
    score: "makes",
    scoreLabel: "Low far-post hits",
    targetNote: "Keep it under cone height",
    space: "18m to goal",
    modes: {
      solo: { setup: "Use bags or cones as far-post target.", cue: "Any ball over hip height is a miss." },
      partner: { setup: "Partner rolls a paced ball from the corner of the box.", cue: "Strike first or second touch only." },
      trainer: { setup: "Coach varies the roll: underhit, heavy, slightly behind.", cue: "Adjust the plant. Don't swing anyway." },
    },
  },
  {
    id: "shot-weak",
    name: "Weak-foot finishes",
    pillar: "shooting",
    focus: "Inside-foot placement with the non-dominant foot",
    setup: "Cut onto the weak foot from 14m. No strong-foot rescue.",
    equipment: ["ball", "cones", "goal"],
    cues: [
      "Open the hips early so you are not reaching",
      "Shorter backswing, cleaner contact",
      "Aim far post — miss far, never middle",
    ],
    why: "Defenders will show you onto it. Make them pay.",
    timer: { kind: "reps", workSec: 0, restSec: 15, sets: 8 },
    score: "makes",
    scoreLabel: "Weak-foot on target",
    targetNote: "5/8 on target",
    space: "Penalty area",
    modes: {
      solo: { setup: "Start on the strong side so the cut is onto the weak foot.", cue: "If you panic to the strong foot, restart." },
      partner: { setup: "Partner stands as a passive fullback showing you inside.", cue: "Take the invitation and finish." },
      trainer: { setup: "Coach scores contact quality 1–5 every rep.", cue: "Chase 4s, not lucky 1s that go in." },
    },
  },
  {
    id: "shot-cut-in",
    name: "Cut inside and shoot",
    pillar: "shooting",
    focus: "Approach from the channel, drop the shoulder, finish",
    setup: "Start wide at 20m. Dribble at a cone fullback, cut inside, shoot before the next cone.",
    equipment: ["ball", "cones", "goal"],
    cues: [
      "Sell the line with the first two touches",
      "Cut is a small touch, not a 5m rewind",
      "Head up once, then strike",
    ],
    why: "This is the pattern that creates goals from wide half-spaces.",
    timer: { kind: "interval", workSec: 25, restSec: 20, sets: 8 },
    score: "makes",
    scoreLabel: "On-target after the cut",
    targetNote: "Shot before the penalty spot",
    space: "Wide channel into the box",
    modes: {
      solo: { setup: "Cone fullback at 16m. Cut must beat the cone.", cue: "If the touch is huge, the shot is cancelled." },
      partner: { setup: "Live 50 percent fullback.", cue: "Attacker must shoot in three touches after the cut." },
      trainer: { setup: "Coach dictates starting side each rep.", cue: "Both channels. No hiding on the favorite." },
    },
  },
  {
    id: "shot-one-touch",
    name: "One-touch finish",
    pillar: "shooting",
    focus: "Redirect a served ball with the inside foot",
    setup: "Start on the penalty spot. Serve from the side or self-drop. One touch only.",
    equipment: ["ball", "goal"],
    cues: [
      "Get in line early, don't stab late",
      "Ankle firm — this is a redirect, not a swing",
      "Aim for the far third of the goal",
    ],
    why: "Box goals are ugly and fast. One-touch is how they get scored.",
    timer: { kind: "reps", workSec: 0, restSec: 12, sets: 10 },
    score: "makes",
    scoreLabel: "One-touch on target",
    targetNote: "6/10 on target",
    space: "6-yard and penalty spot",
    modes: {
      solo: { setup: "Self-toss slightly in front. No bounce-and-blast.", cue: "If you take two touches, walk it back." },
      partner: { setup: "Firm side-foot serve along the ground.", cue: "Server is responsible for a playable ball." },
      trainer: { setup: "Mix ground and skipped balls.", cue: "Body shape first. Contact second." },
    },
  },
  {
    id: "speed-10",
    name: "10m first step",
    pillar: "speed",
    focus: "Acceleration mechanics from a still or rolling start",
    setup: "Two cones at 0 and 10m. Two-point stance. Drive out, then walk-back recovery.",
    equipment: ["cones"],
    cues: [
      "First step is down and back, not up",
      "Arms punch, chin tucked, eyes 5m ahead",
      "Full recovery. Speed work is not conditioning",
    ],
    why: "Most youth sprints that matter are 8–15m. Own the first three steps.",
    timer: { kind: "countdown", workSec: 4, restSec: 40, sets: 6 },
    score: "time",
    scoreLabel: "Best 10m",
    targetNote: "Walk back. No jogging the rest.",
    space: "15m lane",
    modes: {
      solo: { setup: "Phone at the finish for a timer or a parent clap.", cue: "Log only fully recovered reps." },
      partner: { setup: "Staggered starts. Chase, don't dive.", cue: "Winner is first to 10m with a good shape." },
      trainer: { setup: "Coach times and films from the side.", cue: "Kill the set if posture collapses." },
    },
  },
  {
    id: "speed-flying",
    name: "Flying 20",
    pillar: "speed",
    focus: "Max velocity after a 15m build",
    setup: "Build 15m, fly 20m, decelerate 15m. One quality rep at a time.",
    equipment: ["cones"],
    cues: [
      "Build is smooth — do not jump to top speed at step one",
      "Tall in the fly zone, cycle the legs",
      "Decelerate on purpose. Don't crash-stop",
    ],
    why: "When the game opens, you have to run. Learn to be fast without falling apart.",
    timer: { kind: "countdown", workSec: 8, restSec: 75, sets: 4 },
    score: "time",
    scoreLabel: "Fly-zone time",
    targetNote: "Full rest. Quality or skip the rep.",
    space: "50m lane",
    modes: {
      solo: { setup: "Mark build / fly / stop with three colors.", cue: "If the lane is short, do flying 10s." },
      partner: { setup: "Alternate so rest stays honest.", cue: "Do not race the build zone." },
      trainer: { setup: "Coach stands at the fly start.", cue: "Send only when breathing is under control." },
    },
  },
  {
    id: "speed-w",
    name: "W-sprint",
    pillar: "speed",
    focus: "Accelerate, stop, re-accelerate on angles",
    setup: "Five cones in a W, 5m segments. Sprint every leg, plant outside the cone.",
    equipment: ["cones"],
    cues: [
      "Break down one step early",
      "Plant outside, push back in",
      "Eyes up on the next cone — not at your feet",
    ],
    why: "Soccer speed is rarely a straight hallway. This is game speed.",
    timer: { kind: "interval", workSec: 12, restSec: 40, sets: 5 },
    score: "time",
    scoreLabel: "Best W",
    targetNote: "Clean plants, no slipping",
    space: "15x8m",
    modes: {
      solo: { setup: "Time the full W. False step at a cone = no time.", cue: "Chase clean, then chase fast." },
      partner: { setup: "Mirror starts. Second player goes on the first's finish.", cue: "Keep rest real." },
      trainer: { setup: "Coach can flip the W direction mid-block.", cue: "Watch the plant foot, not the clock." },
    },
  },
  {
    id: "agi-ladder",
    name: "Ladder patterns",
    pillar: "agility",
    focus: "Icky shuffle, in-in out-out, lateral two-in",
    setup: "Ladder or 8 taped rungs. Three patterns. Quiet, fast feet. Jog back.",
    equipment: ["ladder"],
    cues: [
      "Stay on the balls of the feet",
      "Arms help — they are not decoration",
      "Rhythm first. Blur second",
    ],
    why: "Foot speed is useless if it's noisy. Quiet feet transfer to the ball.",
    timer: { kind: "interval", workSec: 20, restSec: 20, sets: 8 },
    score: "quality",
    scoreLabel: "Clean rungs",
    targetNote: "Zero missed rungs on the last two sets",
    space: "10m",
    modes: {
      solo: { setup: "No ladder? Use sticks or chalk rungs.", cue: "If you miss, restart that pattern." },
      partner: { setup: "Follow-the-leader. Leader changes pattern each set.", cue: "Stay in the rungs. Don't cheat wide." },
      trainer: { setup: "Coach calls the pattern at the first rung.", cue: "Late call trains the brain, not just the feet." },
    },
  },
  {
    id: "agi-5105",
    name: "5-10-5 cut",
    pillar: "agility",
    focus: "Pro-agility change of direction",
    setup: "Three cones in a line, 5m-5m. Middle start. Touch a line, across, back through middle.",
    equipment: ["cones"],
    cues: [
      "Low on the plant, shin toward the new direction",
      "Don't spin — turn with the hips",
      "Finish through the middle, don't coast",
    ],
    why: "Change of direction is how you lose a marker and how you recover.",
    timer: { kind: "countdown", workSec: 8, restSec: 45, sets: 6 },
    score: "time",
    scoreLabel: "Best 5-10-5",
    targetNote: "Three each starting direction",
    space: "12m line",
    modes: {
      solo: { setup: "Hand down to the cone or a clear line touch.", cue: "No touch, no time." },
      partner: { setup: "Partner starts you with a clap.", cue: "React, don't guess." },
      trainer: { setup: "Coach points the first direction on the clap.", cue: "That is the drill. Don't pre-lean." },
    },
  },
  {
    id: "agi-reactive",
    name: "Reactive color cuts",
    pillar: "agility",
    focus: "See, plant, go",
    setup: "Four colored cones in a diamond, 4m out. Start in the middle. Sprint to the called color, return.",
    equipment: ["cones"],
    cues: [
      "Eyes up — you can't cut what you don't see",
      "Small adjustment steps, then a real plant",
      "Return under control. The next call is coming",
    ],
    why: "Game agility is reactive. Closed drills alone make robots.",
    timer: { kind: "interval", workSec: 20, restSec: 30, sets: 6 },
    score: "quality",
    scoreLabel: "Correct cuts",
    targetNote: "Zero wrong-color sprints",
    space: "10x10m",
    modes: {
      solo: { setup: "Pre-write a color sequence on a card, or use a random color app.", cue: "No looking down at the phone mid-set." },
      partner: { setup: "Partner calls colors. Mix in fakes.", cue: "Honor the real call only." },
      trainer: { setup: "Coach uses hands, not just voice.", cue: "Punish guessing." },
    },
  },
  {
    id: "agi-decel",
    name: "Decel to stick",
    pillar: "agility",
    focus: "Stop on balance, then re-accelerate",
    setup: "Sprint 12m to a stick-zone, two-foot stick for a beat, explode 5m at 45 degrees.",
    equipment: ["cones"],
    cues: [
      "Chop the steps, hips back, chest up",
      "Stick means still — not a stumble",
      "The 45 is a new sprint, not a jog away",
    ],
    why: "Injuries and lost duels both live in sloppy stopping.",
    timer: { kind: "interval", workSec: 12, restSec: 35, sets: 6 },
    score: "quality",
    scoreLabel: "Stuck landings",
    targetNote: "Quiet stick, then violent exit",
    space: "20m",
    modes: {
      solo: { setup: "Use a towel or cone as the stick line.", cue: "If you hop, the rep is a miss." },
      partner: { setup: "Partner stands in the 45-exit lane as a shadow.", cue: "Exit away from the shadow." },
      trainer: { setup: "Coach points the 45 after the stick.", cue: "Hold the stick until the point." },
    },
  },
  {
    id: "str-split",
    name: "Split squat strength",
    pillar: "strength",
    focus: "Single-leg strength the way soccer uses it",
    setup: "Rear foot on the ground. Slow down, drive up. Alternate legs each set.",
    equipment: [],
    cues: [
      "Front heel stays heavy",
      "Knee tracks over the mid-foot",
      "Three seconds down. No bounce",
    ],
    why: "At 13, strength is control. This builds the legs that win contact.",
    timer: { kind: "reps", workSec: 40, restSec: 30, sets: 6 },
    score: "reps",
    scoreLabel: "Quality reps per leg",
    targetNote: "8–12 each side, slow",
    space: "Yoga-mat sized",
    modes: {
      solo: { setup: "Hand on a wall only if you lose balance.", cue: "Earn the free-standing set." },
      partner: { setup: "Face each other. Match tempo.", cue: "If your partner rushes, you both restart." },
      trainer: { setup: "Coach counts the eccentric out loud.", cue: "Stop the set at the first collapse." },
    },
  },
  {
    id: "str-hinge",
    name: "Single-leg hinge",
    pillar: "strength",
    focus: "Hamstring and hip control",
    setup: "Athletic stance, hinge on one leg, other leg reaches back. Soft knee. Stand tall.",
    equipment: [],
    cues: [
      "Hips go back, not down",
      "Hips stay square — don't open like a gate",
      "Feel the standing hamstring, not the low back",
    ],
    why: "Sprinting and shooting both live in the hinge. Own it on one leg.",
    timer: { kind: "reps", workSec: 40, restSec: 25, sets: 4 },
    score: "reps",
    scoreLabel: "Controlled hinges",
    targetNote: "6–8 each side without a wobble dump",
    space: "Yoga-mat sized",
    modes: {
      solo: { setup: "Fingertips to a wall if needed for the first set.", cue: "Quality over depth." },
      partner: { setup: "Partner watches hip square from behind.", cue: "Call 'open' if the hip spins." },
      trainer: { setup: "Coach can add a light ball reach to the floor.", cue: "The ball is a target, not a weight." },
    },
  },
  {
    id: "str-core",
    name: "Core brace circuit",
    pillar: "strength",
    focus: "Dead bug, side plank, hollow hold",
    setup: "Mat. Dead bug 30s, side plank 20s each, hollow 20s. That is one set.",
    equipment: [],
    cues: [
      "Ribs down. If the back rips off the floor, shrink the range",
      "Side plank is a straight line, not a sagging hammock",
      "Breathe. A brace that can't breathe is a panic",
    ],
    why: "Core is how power from the ground gets to the ball.",
    timer: { kind: "interval", workSec: 70, restSec: 25, sets: 3 },
    score: "quality",
    scoreLabel: "Brace quality",
    targetNote: "No sag, no breath-hold",
    space: "Yoga-mat sized",
    modes: {
      solo: { setup: "Phone at the side for the timer. Stay on the mat.", cue: "Reset the shape, not the clock, if you sag." },
      partner: { setup: "One works, one coaches the shape.", cue: "Swap every set." },
      trainer: { setup: "Coach taps the ribs if they flare.", cue: "Shape over time." },
    },
  },
  {
    id: "str-pogo",
    name: "Pogo and land",
    pillar: "strength",
    focus: "Elastic calves + quiet landing",
    setup: "Stiff ankles, small pogos in place, then a stick landing on two feet, then one.",
    equipment: [],
    cues: [
      "Think fast ground, not high jump",
      "Land like the floor is a quiet library",
      "Knees out a hint. No knock-kneed stick",
    ],
    why: "Repeat sprints need spring. Landings need control. This is both.",
    timer: { kind: "interval", workSec: 20, restSec: 25, sets: 6 },
    score: "quality",
    scoreLabel: "Quiet sticks",
    targetNote: "Last two landings silent",
    space: "2x2m",
    modes: {
      solo: { setup: "Grass or turf preferred. Skip if the surface is slick.", cue: "Stop if anything in the foot or shin complains." },
      partner: { setup: "Match bounce rhythm, then race who sticks quieter.", cue: "Quiet beats high." },
      trainer: { setup: "Coach listens more than watches.", cue: "Noise is feedback." },
    },
  },
  {
    id: "str-push",
    name: "Upper-body work",
    pillar: "strength",
    focus: "Push-ups and shoulder-friendly rows if a table is available",
    setup: "Push-up sets with a hard brace. If you have a sturdy table, inverted rows after.",
    equipment: [],
    cues: [
      "Body one piece — hips don't sag or pike",
      "Chest to a fist off the floor, not a neck crane",
      "If regular push-ups break, elevate the hands and keep the line",
    ],
    why: "Shielding, throw-ins, and winning the floor all need an upper body that can brace.",
    timer: { kind: "reps", workSec: 35, restSec: 30, sets: 4 },
    score: "reps",
    scoreLabel: "Clean push-ups",
    targetNote: "Leave two in the tank",
    space: "Yoga-mat sized",
    modes: {
      solo: { setup: "Hands under shoulders. Film one set from the side if you can.", cue: "Ugly reps don't count." },
      partner: { setup: "Partner's fist is the chest target.", cue: "They call sag immediately." },
      trainer: { setup: "Coach picks the elevation so every rep is clean.", cue: "This is not a max-out." },
    },
  },
  {
    id: "fin-rondo-shadow",
    name: "Pressure box",
    pillar: "ball",
    focus: "Keep the ball in a shrinking space",
    setup: "6x6m box. Stay inside with the ball. Add feints. If it leaves, sprint a 10m tax and restart.",
    equipment: ["ball", "cones"],
    cues: [
      "Body between ball and the imaginary defender",
      "Change speed every 4–5 touches",
      "Find the exit before you need it",
    ],
    why: "This is the messy middle of a match, compressed.",
    timer: { kind: "interval", workSec: 45, restSec: 20, sets: 4 },
    score: "reps",
    scoreLabel: "Box exits without a tax",
    targetNote: "Stay in for the full work bout",
    space: "6x6m",
    modes: {
      solo: { setup: "Shrink the box by a step each set.", cue: "Tax run is honest or the drill is fake." },
      partner: { setup: "1v1 in the box. Possession 45s.", cue: "No fouls. Body, not hands." },
      trainer: { setup: "Coach steps in as a bump defender late.", cue: "Hold them up, don't take them out." },
    },
  },
  {
    id: "fin-shoot-game",
    name: "Ten-ball game",
    pillar: "shooting",
    focus: "Mixed finishes under a scoreboard",
    setup: "Ten balls. Mix: 3 placement, 3 driven, 2 weak-foot, 2 one-touch. Track a score.",
    equipment: ["ball", "cones", "goal"],
    cues: [
      "Call the type before you start the run",
      "Reset your feet. Don't rush the last three",
      "Chase the personal record, not a highlight",
    ],
    why: "A scoreboard makes practice honest. This is the session you remember.",
    timer: { kind: "reps", workSec: 0, restSec: 10, sets: 10 },
    score: "makes",
    scoreLabel: "Points / 10",
    targetNote: "Beat last week's score",
    space: "Penalty area",
    modes: {
      solo: { setup: "Line up whatever balls you have and reuse.", cue: "Write the score before you forget it." },
      partner: { setup: "Alternate shots. Running total.", cue: "Loser starts the next session's cones." },
      trainer: { setup: "Coach assigns the mix live.", cue: "Raise the standard if 8/10 is too easy." },
    },
  },
  {
    id: "cool-mobility",
    name: "Downshift",
    pillar: "strength",
    focus: "Hips, calves, breathing",
    setup: "90/90 hips, calf stretch on a curb, easy walk. Nasal breathing if you can.",
    equipment: [],
    cues: [
      "You are not done until breathing is quiet",
      "Stretch what you actually used",
      "One thing you did well. One thing tomorrow fixes",
    ],
    why: "Recovery is part of the work. Elite kids learn this early.",
    timer: { kind: "interval", workSec: 60, restSec: 0, sets: 3 },
    score: "none",
    targetNote: "Leave better than you arrived",
    space: "Anywhere",
    modes: {
      solo: { setup: "Sit down. Don't scroll yet.", cue: "Log the session before the phone eats you." },
      partner: { setup: "Walk the field and talk one cue that mattered.", cue: "Then you're done." },
      trainer: { setup: "Coach asks for the player's own note first.", cue: "They should be able to coach themselves." },
    },
  },
];

export const DRILL_MAP: Record<string, Drill> = Object.fromEntries(
  DRILLS.map((d) => [d.id, d]),
);

export function getDrill(id: string): Drill {
  const d = DRILL_MAP[id];
  if (!d) throw new Error(`Unknown drill: ${id}`);
  return d;
}
