/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DrillsRouteImport } from './routes/drills'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as DrillsDrillIdRouteImport } from './routes/drills.$drillId'
import { Route as SessionSessionIdRouteImport } from './routes/session.$sessionId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillsRoute = DrillsRouteImport.update({
  id: '/drills',
  path: '/drills',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillsDrillIdRoute = DrillsDrillIdRouteImport.update({
  id: '/$drillId',
  path: '/$drillId',
  getParentRoute: () => DrillsRoute,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drills': typeof DrillsRouteWithChildren
  '/login': typeof LoginRoute
  '/program': typeof ProgramRoute
  '/tracker': typeof TrackerRoute
  '/videos': typeof VideosRoute
  '/drills/$drillId': typeof DrillsDrillIdRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drills': typeof DrillsRouteWithChildren
  '/login': typeof LoginRoute
  '/program': typeof ProgramRoute
  '/tracker': typeof TrackerRoute
  '/videos': typeof VideosRoute
  '/drills/$drillId': typeof DrillsDrillIdRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drills': typeof DrillsRouteWithChildren
  '/login': typeof LoginRoute
  '/program': typeof ProgramRoute
  '/tracker': typeof TrackerRoute
  '/videos': typeof VideosRoute
  '/drills/$drillId': typeof DrillsDrillIdRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/drills'
    | '/login'
    | '/program'
    | '/tracker'
    | '/videos'
    | '/drills/$drillId'
    | '/session/$sessionId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/drills'
    | '/login'
    | '/program'
    | '/tracker'
    | '/videos'
    | '/drills/$drillId'
    | '/session/$sessionId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/drills'
    | '/login'
    | '/program'
    | '/tracker'
    | '/videos'
    | '/drills/$drillId'
    | '/session/$sessionId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DrillsRoute: typeof DrillsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProgramRoute: typeof ProgramRoute
  TrackerRoute: typeof TrackerRoute
  VideosRoute: typeof VideosRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drills': {
      id: '/drills'
      path: '/drills'
      fullPath: '/drills'
      preLoaderRoute: typeof DrillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drills/$drillId': {
      id: '/drills/$drillId'
      path: '/$drillId'
      fullPath: '/drills/$drillId'
      preLoaderRoute: typeof DrillsDrillIdRouteImport
      parentRoute: typeof DrillsRoute
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DrillsRouteChildren {
  DrillsDrillIdRoute: typeof DrillsDrillIdRoute
}

const DrillsRouteChildren: DrillsRouteChildren = {
  DrillsDrillIdRoute: DrillsDrillIdRoute,
}

const DrillsRouteWithChildren =
  DrillsRoute._addFileChildren(DrillsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DrillsRoute: DrillsRouteWithChildren,
  LoginRoute: LoginRoute,
  ProgramRoute: ProgramRoute,
  TrackerRoute: TrackerRoute,
  VideosRoute: VideosRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
